services:
  postgres-db:
    image: postgres:16-alpine
    container_name: tasklume-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: tasklume_user
      POSTGRES_PASSWORD: tasklume_password
      POSTGRES_DB: tasklume_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U tasklume_user -d tasklume_db']
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tasklume-backend
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://tasklume_user:tasklume_password@postgres-db:5432/tasklume_db?schema=public
    depends_on:
      postgres-db:
        condition: service_healthy

volumes:
  postgres-data:
